// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrWAZeSza49UZC7oRUqu56XDxegO9zZ6c',
    appId: '1:726556693164:web:17b95bfe49072aff874509',
    messagingSenderId: '726556693164',
    projectId: 'leafy-house',
    authDomain: 'leafy-house.firebaseapp.com',
    storageBucket: 'leafy-house.firebasestorage.app',
    measurementId: 'G-80MJC0DXV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqJx1Wc7v_JE4ihEwASRTuoq4XMu4SD_s',
    appId: '1:726556693164:android:db672d7feb86ab68874509',
    messagingSenderId: '726556693164',
    projectId: 'leafy-house',
    storageBucket: 'leafy-house.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOiOuU7c_otzBVJ1zyPlsO4-H5PkpDvNU',
    appId: '1:726556693164:ios:e0c46a4caf08eed9874509',
    messagingSenderId: '726556693164',
    projectId: 'leafy-house',
    storageBucket: 'leafy-house.firebasestorage.app',
    iosBundleId: 'com.example.leafyHouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOiOuU7c_otzBVJ1zyPlsO4-H5PkpDvNU',
    appId: '1:726556693164:ios:e0c46a4caf08eed9874509',
    messagingSenderId: '726556693164',
    projectId: 'leafy-house',
    storageBucket: 'leafy-house.firebasestorage.app',
    iosBundleId: 'com.example.leafyHouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrWAZeSza49UZC7oRUqu56XDxegO9zZ6c',
    appId: '1:726556693164:web:0556dab8751a9032874509',
    messagingSenderId: '726556693164',
    projectId: 'leafy-house',
    authDomain: 'leafy-house.firebaseapp.com',
    storageBucket: 'leafy-house.firebasestorage.app',
    measurementId: 'G-T2JT7VEXYP',
  );
}
